sudo: false
language: c
cache:
  directories:
  - "$HOME/.stack"
  - "$HOME/build/serokell/time-warp/.stack-work"
addons:
  apt:
    packages:
    - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards
  --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal --install-ghc install happy --jobs=4
- stack --no-terminal --install-ghc build --only-dependencies --jobs=4
script:
- stack --no-terminal build --test --haddock --no-haddock-deps --bench --jobs=4
    --flag time-warp:build-executables
notifications:
  email: false
  slack:
    rooms:
      - serokell:Lk0GI0786tPYo9Nve9SSuPOf
    on_success: change
    on_failure: always
